import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, ArrowUpRight, Bell, Check, CheckCircle2, ChevronDown, ChevronRight, Clock3, LayoutDashboard, LogOut, Menu, MoreHorizontal, Plus, RotateCcw, ScanFace, Search, Settings, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import Landing, { Brand } from './Landing';
import { download, type Attendance } from './api';
import { DEMO_DATE, demoMark, filterRecords, formatTime, initialRecords, initials, people as initialPeople, type DemoPerson } from './demo';

type Page = 'Overview' | 'Attendance' | 'People' | 'Attendance station' | 'Settings';
const navigation = [
  { label: 'Overview' as Page, icon: LayoutDashboard }, { label: 'Attendance' as Page, icon: Clock3 },
  { label: 'People' as Page, icon: Users }, { label: 'Attendance station' as Page, icon: ScanFace },
];

export default function App() {
  const [demo, setDemo] = useState(window.location.hash === '#demo');
  useEffect(() => { const onHash = () => { setDemo(window.location.hash === '#demo'); window.scrollTo(0, 0); }; window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  return demo ? <Workspace back={() => { window.location.hash = ''; }} /> : <Landing open={() => { window.location.hash = 'demo'; }} />;
}

function Workspace({ back }: { back: () => void }) {
  const [page, setPage] = useState<Page>('Overview');
  const [records, setRecords] = useState<Attendance[]>(initialRecords);
  const [people, setPeople] = useState<DemoPerson[]>(initialPeople);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('All statuses');
  const [date, setDate] = useState(DEMO_DATE);
  const [addPerson, setAddPerson] = useState(false);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [notice, setNotice] = useState('');
  const [workspaceName, setWorkspaceName] = useState('Acme Studio');
  const filtered = filterRecords(records, search, status, date);
  const notify = (message: string) => setNotice(message);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 5500); return () => clearTimeout(timer); }, [notice]);
  const navigate = (next: Page) => { setPage(next); setMobileMenu(false); setSearch(''); };
  const exportRecords = () => { download(filtered); notify('Sample attendance exported as CSV.'); };

  return <div className="workspace">
    {mobileMenu && <button className="sidebar-backdrop" onClick={() => setMobileMenu(false)} aria-label="Close navigation" />}
    <aside className={`sidebar ${mobileMenu ? 'sidebar-open' : ''}`}><button className="brand-button" onClick={back}><Brand /></button><div className="workspace-picker"><span className="workspace-avatar">{initials(workspaceName)}</span><div><strong>{workspaceName}</strong><small>Example workspace</small></div><ChevronDown size={15} /></div><span className="nav-label">WORKSPACE</span><nav>{navigation.map(item => <button key={item.label} className={page === item.label ? 'active' : ''} onClick={() => navigate(item.label)}><item.icon size={18} />{item.label}{page === item.label && <span className="nav-dot" />}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-tip"><span><Sparkles size={17} /> Meet your new workday</span><p>Take a look around. Everything here is safe to explore.</p><button onClick={() => navigate('Attendance station')}>Try a check-in <ArrowRight size={15} /></button></div><button className={`settings-nav ${page === 'Settings' ? 'active' : ''}`} onClick={() => navigate('Settings')}><Settings size={18} /> Settings</button><button className="settings-nav" onClick={back}><ArrowLeft size={18} /> Back to website</button><div className="profile"><span className="avatar mint">AD</span><div><strong>Alex Demo</strong><small>Workspace administrator</small></div><span className="green-dot" /></div></div></aside>
    <div className="workspace-main"><header className="workspace-header"><button className="icon-button mobile-toggle" onClick={() => setMobileMenu(true)} aria-label="Open navigation"><Menu size={22} /></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={14} /><strong>{page}</strong></div><div className="header-right"><span className="badge neutral">Interactive preview</span><button className="icon-button" aria-label="Show notifications" onClick={() => notify('You’re all caught up. This preview has no live notifications.')}><Bell size={19} /></button><span className="avatar small mint">AD</span></div></header>
      <div className="demo-banner"><span><Sparkles size={14} /><strong>You're exploring a demo.</strong> All people and records are fictional. Changes reset on refresh.</span><button onClick={() => { setRecords(initialRecords); setPeople(initialPeople); setWorkspaceName('Acme Studio'); setDate(DEMO_DATE); setSearch(''); setStatus('All statuses'); notify('Demo restored to its starting point.'); }}><RotateCcw size={13} /> Reset demo</button></div>
      <main className="dashboard-content">
        <div className="page-heading"><div><span className="overline">MONDAY, OCTOBER 5, 2026 · SAMPLE DAY</span><h1>{page === 'Overview' ? 'A good day starts with your people.' : page === 'People' ? 'Your team, all in one place.' : page === 'Attendance station' ? 'A warm welcome. A simple check-in.' : page === 'Settings' ? 'Make this workspace yours.' : 'Every arrival. Every departure.'}</h1><p>{page === 'Overview' ? "Here's how your team’s day is taking shape." : page === 'People' ? 'Manage the people who make your workplace work.' : page === 'Attendance station' ? 'Explore the attendance experience without using your camera.' : page === 'Settings' ? 'Preview your workspace preferences.' : 'Find, review, and export the records you need.'}</p></div>{page !== 'Settings' && page !== 'Attendance station' && <button className="button dark" onClick={page === 'People' ? () => setAddPerson(true) : exportRecords}>{page === 'People' ? <Plus size={16} /> : <ArrowDownToLine size={16} />}{page === 'People' ? 'Add person' : 'Export report'}</button>}</div>
        {page === 'Overview' && <><div className="stat-grid"><Stat title="Team members" value={people.length} icon={<Users size={19} />} foot="People in your workspace" /><Stat title="Checked in today" value={records.length} icon={<CheckCircle2 size={19} />} foot={`${Math.round(records.length / people.length * 100)}% of your team`} green /><Stat title="Currently at work" value={records.filter(row => !row.sign_out_time).length} icon={<Clock3 size={19} />} foot="Checked in, not yet out" /><Stat title="Checked out" value={records.filter(row => row.sign_out_time).length} icon={<LogOut size={19} />} foot="Workday completed" /></div><div className="overview-grid"><AttendanceChart today={records.length} /><div className="station-promo"><div className="promo-icon"><ScanFace size={29} /></div><span className="badge mint-badge">READY WHEN YOU ARE</span><h2>A smoother way<br />to start the day.</h2><p>Try the check-in experience<br />at your attendance station.</p><button className="button dark" onClick={() => navigate('Attendance station')}>Open station <ArrowUpRight size={16} /></button><span className="promo-rings" /></div></div></>}
        {(page === 'Overview' || page === 'Attendance') && <section className="panel records-panel"><div className="panel-heading"><div><h2>{page === 'Overview' ? "Today's activity" : 'Attendance records'} <span className="count">{filtered.length}</span></h2><p>Verified arrivals and departures for your sample team.</p></div><button className="icon-button" aria-label="Export sample attendance" onClick={exportRecords}><MoreHorizontal size={21} /></button></div><div className="table-toolbar"><label className="search-field"><Search size={17} /><input placeholder="Search name or employee ID..." aria-label="Search attendance" value={search} onChange={e => setSearch(e.target.value)} /></label><div className="filter-group"><input type="date" aria-label="Attendance date" value={date} onChange={e => setDate(e.target.value)} /><select aria-label="Attendance status" value={status} onChange={e => setStatus(e.target.value)}><option>All statuses</option><option>Checked in</option><option>Checked out</option></select></div></div><RecordsTable records={filtered} people={people} /><div className="table-footer"><span>Showing {filtered.length} of {records.length} sample records</span><span><ShieldCheck size={14} /> Sample verified status</span></div></section>}
        {page === 'People' && <section className="panel"><div className="panel-heading"><div><h2>Team directory <span className="count">{people.length}</span></h2><p>Fictional people, ready for you to explore.</p></div><label className="search-field"><Search size={17} /><input placeholder="Find a person..." aria-label="Search people" value={search} onChange={e => setSearch(e.target.value)} /></label></div><div className="people-grid">{people.filter(p => `${p.name} ${p.employee_id} ${p.department}`.toLowerCase().includes(search.toLowerCase())).map(person => <article className="person-card" key={person.id}><span className={`avatar large ${person.color}`}>{initials(person.name)}</span><h3>{person.name}</h3><span>{person.department}</span><small>{person.employee_id}</small><div><span className="badge mint-badge"><Check size={12} /> Sample enrollment</span><button className="icon-button" aria-label={`View ${person.name}`} onClick={() => { navigate('Attendance'); setSearch(person.employee_id); }}><ArrowUpRight size={17} /></button></div></article>)}</div>{!people.some(p => `${p.name} ${p.employee_id} ${p.department}`.toLowerCase().includes(search.toLowerCase())) && <div className="empty-state"><Users /><h3>No matching people</h3><p>Try a different name, department, or ID.</p></div>}</section>}
        {page === 'Attendance station' && <Station people={people} onMark={(person, action) => { const result = demoMark(records, person, action); setRecords(result.records); return result; }} />}
        {page === 'Settings' && <SettingsPanel name={workspaceName} onSave={name => { setWorkspaceName(name); notify('Workspace name updated for this demo session.'); }} />}
        <footer className="dashboard-footer"><span><span className="green-dot" /> FaceTrack product showcase</span><span>Thoughtfully built for the way teams work.</span></footer>
      </main>
    </div>{notice && <div className="toast" role="status"><CheckCircle2 size={19} /><span>{notice}</span><button aria-label="Dismiss notification" onClick={() => setNotice('')}><X size={16} /></button></div>}
    {addPerson && <AddPerson people={people} close={() => setAddPerson(false)} save={person => { setPeople([...people, person]); setAddPerson(false); notify(`${person.name} added to the sample team. No biometric data collected.`); }} />}
  </div>;
}

function Stat({ title, value, icon, foot, green }: { title: string; value: number; icon: React.ReactNode; foot: string; green?: boolean }) {
  return <article className={`stat-card ${green ? 'stat-green' : ''}`}><div><span>{title}</span><span className="stat-icon">{icon}</span></div><strong>{value.toString().padStart(2, '0')}</strong><small>{green && <span className="green-dot" />}{foot}</small></article>;
}

function AttendanceChart({ today }: { today: number }) {
  const [range, setRange] = useState('This week');
  const values = range === 'This week' ? [5, 7, 6, 8, 7, 4, today] : [22, 30, 25, 35, 29, 32, 28];
  const labels = range === 'This week' ? ['Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Mon'] : ['W1', 'W2', 'W3', 'W4', 'W5', 'W6', 'W7'];
  const max = range === 'This week' ? Math.max(8, today) : 40;
  return <section className="panel chart-panel"><div className="panel-heading"><div><h2>Attendance pulse</h2><p>A little perspective on your team's rhythm.</p></div><select aria-label="Chart period" value={range} onChange={e => setRange(e.target.value)}><option>This week</option><option>Last 7 weeks</option></select></div><div className="chart-legend"><span><i /> Check-ins</span><small>Illustrative history · not live data</small></div><div className="bar-chart" role="img" aria-label={`Sample attendance: ${values.map((n, i) => `${labels[i]} ${n}`).join(', ')}`}><div className="chart-grid">{[max, Math.round(max * .75), Math.round(max * .5), Math.round(max * .25), 0].map((n, i) => <div key={i}><span>{n}</span><i /></div>)}</div><div className="chart-bars">{values.map((n, i) => <div className="chart-column" key={i}><div className={`chart-bar ${i === 6 ? 'bar-active' : ''}`} style={{ height: `${n / max * 100}%` }}><span>{n}</span></div><small>{labels[i]}</small></div>)}</div></div></section>;
}

function RecordsTable({ records, people }: { records: Attendance[]; people: DemoPerson[] }) {
  return <div className="table-scroll"><table><thead><tr><th>Team member</th><th>Employee ID</th><th>Check-in</th><th>Check-out</th><th>Status</th><th>Verification</th></tr></thead><tbody>{records.map(row => { const person = people.find(p => p.employee_id === row.employee_id); return <tr key={`${row.employee_id}-${row.date}`}><td><div className="table-person"><span className={`avatar ${person?.color || 'mint'}`}>{initials(row.name)}</span><div><strong>{row.name}</strong><small>{person?.department || 'Team'}</small></div></div></td><td className="muted mono">{row.employee_id}</td><td>{formatTime(row.sign_in_time)}</td><td className={!row.sign_out_time ? 'muted' : ''}>{formatTime(row.sign_out_time)}</td><td><span className={`badge ${row.sign_out_time ? 'neutral' : 'mint-badge'}`}><span className="status-dot" />{row.sign_out_time ? 'Checked out' : 'Checked in'}</span></td><td><span className="verification"><ShieldCheck size={15} /> Verified <small>(sample)</small></span></td></tr>; })}</tbody></table>{!records.length && <div className="empty-state"><Search /><h3>No records found</h3><p>Try another search, status, or date. Sample records start on October 5, 2026.</p></div>}</div>;
}

function Station({ people, onMark }: { people: DemoPerson[]; onMark: (person: DemoPerson, action: 'in' | 'out') => { message: string; success: boolean } }) {
  const [personId, setPersonId] = useState(people[people.length - 1].id);
  const [action, setAction] = useState<'in' | 'out'>('in');
  const [stage, setStage] = useState(0);
  const [message, setMessage] = useState('');
  const [success, setSuccess] = useState(false);
  const running = stage > 0 && stage < 4;
  const markRef = useRef(onMark); markRef.current = onMark;
  const person = people.find(p => p.id === personId)!;
  useEffect(() => {
    if (!running) return;
    const timer = setTimeout(() => {
      if (stage === 3) { const result = markRef.current(person, action); setMessage(result.message); setSuccess(result.success); }
      setStage(current => current + 1);
    }, 1200);
    return () => clearTimeout(timer);
  }, [stage, running, person, action]);
  return <div className="station-layout"><section className="panel station-screen"><div className="panel-heading"><h2><ScanFace size={20} /> Attendance station</h2><span className="badge neutral">Simulation</span></div><div className={`camera-preview ${running ? 'scanning' : ''} ${stage === 4 && success ? 'scan-success' : ''}`}><div className="camera-grid" /><div className="face-outline"><ScanFace size={145} strokeWidth={.8} /><i /><i /><i /><i /></div>{running && <div className="camera-scan" />}<div className="camera-status"><span className="green-dot" /> {stage === 0 ? 'Ready to explore' : stage === 1 ? 'Face detection preview…' : stage === 2 ? 'Movement challenge preview…' : stage === 3 ? 'Preparing sample attendance…' : success ? 'Sample attendance updated' : 'Attendance rule checked'}</div></div><div className="station-disclaimer"><ShieldCheck size={17} /><span>Animation only. This demo does not open your camera, verify a face, or collect biometric data.</span></div></section><section className="panel station-controls"><span className="overline">TRY IT YOURSELF</span><h2>A check-in in<br />a few simple steps.</h2><p>Choose a fictional team member and see how attendance moves through the workspace.</p><label>Sample team member<select disabled={running} value={personId} onChange={e => { setPersonId(Number(e.target.value)); setStage(0); setMessage(''); }}>{people.map(p => <option key={p.id} value={p.id}>{p.name} · {p.employee_id}</option>)}</select></label><label>Attendance action</label><div className="segmented"><button disabled={running} className={action === 'in' ? 'selected' : ''} onClick={() => { setAction('in'); setStage(0); setMessage(''); }}>Check in</button><button disabled={running} className={action === 'out' ? 'selected' : ''} onClick={() => { setAction('out'); setStage(0); setMessage(''); }}>Check out</button></div><button className="button dark full" disabled={running} onClick={() => { setMessage(''); setStage(1); }}><ScanFace size={18} />{running ? 'Preview in progress…' : `Preview check-${action}`}</button>{message && <div className={`feedback ${success ? 'feedback-success' : ''}`} role="status">{success ? <CheckCircle2 size={18} /> : <Clock3 size={18} />}{message}</div>}<div className="station-steps">{['Detect a single face', 'Complete the movement challenge', 'Record the attendance'].map((text, i) => <div key={text}><span className={stage > i ? 'step-done' : ''}>{stage > i ? <Check size={12} /> : i + 1}</span>{text}</div>)}</div></section></div>;
}

function SettingsPanel({ name, onSave }: { name: string; onSave: (name: string) => void }) {
  const [draft, setDraft] = useState(name);
  useEffect(() => { setDraft(name); }, [name]);
  return <div className="settings-layout"><form className="panel settings-panel" onSubmit={e => { e.preventDefault(); if (draft.trim()) onSave(draft.trim()); }}><div className="panel-heading"><div><h2>Workspace details</h2><p>Personalize the sample workspace during your presentation.</p></div></div><div className="form-body"><label>Workspace name<input required maxLength={40} value={draft} onChange={e => setDraft(e.target.value)} /></label><label>Timezone<input readOnly value="Asia/Karachi (UTC +05:00)" /></label><label>Workspace mode<input readOnly value="Public showcase · fictional data" /></label><p className="form-note">These settings are only a preview. Nothing is saved to a server.</p><button className="button dark" type="submit">Save preview settings <Check size={16} /></button></div></form><aside className="panel settings-info"><ShieldCheck size={29} /><h3>A clear line between<br />preview and production.</h3><p>This showcase is designed for client presentations. It runs entirely in your browser with fictional records.</p><ul><li>No passwords required</li><li>No camera or biometric collection</li><li>No real employee records</li><li>Refresh to reset your changes</li></ul><small>The Python recognition application is a separate system. Connecting real attendance requires a hosted backend and deployment review.</small></aside></div>;
}

function AddPerson({ people, close, save }: { people: DemoPerson[]; close: () => void; save: (person: DemoPerson) => void }) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const [name, setName] = useState(''); const [id, setId] = useState(''); const [department, setDepartment] = useState('Design'); const [error, setError] = useState('');
  useEffect(() => { dialogRef.current?.showModal(); }, []);
  function submit(e: FormEvent) { e.preventDefault(); const employeeId = id.trim().toUpperCase(); if (!name.trim() || !/^[A-Z0-9][A-Z0-9_-]{1,31}$/.test(employeeId)) { setError('Enter a name and a 2–32 character ID using letters, numbers, hyphens or underscores.'); return; } if (people.some(p => p.employee_id === employeeId)) { setError('That employee ID is already in this sample team.'); return; } save({ id: Math.max(...people.map(p => p.id)) + 1, name: name.trim(), employee_id: employeeId, department, color: 'lavender', created_at: DEMO_DATE }); }
  return <dialog ref={dialogRef} className="modal" onCancel={close} onClick={e => { if (e.target === e.currentTarget) close(); }}><div className="modal-heading"><span className="feature-icon"><Users size={24} /></span><button className="icon-button" aria-label="Close add person" onClick={close}><X size={21} /></button></div><h2>A new face on the team.</h2><p>Add a fictional person to explore the workflow. Please don't enter real personal information.</p><form onSubmit={submit}><label>Full name<input autoFocus required maxLength={70} value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Alex Morgan" /></label><label>Employee ID<input required maxLength={32} value={id} onChange={e => setId(e.target.value)} placeholder="e.g. FT-009" /></label><label>Department<select value={department} onChange={e => setDepartment(e.target.value)}>{['Design', 'Engineering', 'Marketing', 'Operations', 'People & HR'].map(d => <option key={d}>{d}</option>)}</select></label>{error && <div className="feedback" role="alert">{error}</div>}<div className="modal-actions"><button className="button outline" type="button" onClick={close}>Cancel</button><button className="button dark" type="submit"><Plus size={16} />Add sample person</button></div></form></dialog>;
}
